

const dummyData =[{
    "id": 1,
    "first_name": "Lanny",
    "last_name": "Foskew",
    "email": "lfoskew0@paypal.com",
    "gender": "Male"
  }, {
    "id": 2,
    "first_name": "Herc",
    "last_name": "Ronaldson",
    "email": "hronaldson1@craigslist.org",
    "gender": "Agender"
  }, {
    "id": 3,
    "first_name": "Shelden",
    "last_name": "Gwilliams",
    "email": "sgwilliams2@blogs.com",
    "gender": "Male"
  }, {
    "id": 4,
    "first_name": "Shelby",
    "last_name": "Gillean",
    "email": "sgillean3@unc.edu",
    "gender": "Female"
  }, {
    "id": 5,
    "first_name": "Fraze",
    "last_name": "Rotchell",
    "email": "frotchell4@canalblog.com",
    "gender": "Male"
  }, {
    "id": 6,
    "first_name": "Gabby",
    "last_name": "Commuzzo",
    "email": "gcommuzzo5@ovh.net",
    "gender": "Male"
  }, {
    "id": 7,
    "first_name": "Rickie",
    "last_name": "Basili",
    "email": "rbasili6@typepad.com",
    "gender": "Male"
  }, {
    "id": 8,
    "first_name": "Giulietta",
    "last_name": "Barczynski",
    "email": "gbarczynski7@huffingtonpost.com",
    "gender": "Female"
  }, {
    "id": 9,
    "first_name": "Minetta",
    "last_name": "Faussett",
    "email": "mfaussett8@tumblr.com",
    "gender": "Female"
  }, {
    "id": 10,
    "first_name": "Ailyn",
    "last_name": "Batter",
    "email": "abatter9@cdc.gov",
    "gender": "Bigender"
  }, {
    "id": 11,
    "first_name": "Stillmann",
    "last_name": "Michelotti",
    "email": "smichelottia@tuttocitta.it",
    "gender": "Male"
  }, {
    "id": 12,
    "first_name": "Debi",
    "last_name": "MacGrath",
    "email": "dmacgrathb@harvard.edu",
    "gender": "Polygender"
  }, {
    "id": 13,
    "first_name": "Wendeline",
    "last_name": "Smiz",
    "email": "wsmizc@goodreads.com",
    "gender": "Genderfluid"
  }, {
    "id": 14,
    "first_name": "Chan",
    "last_name": "Spurge",
    "email": "cspurged@economist.com",
    "gender": "Male"
  }, {
    "id": 15,
    "first_name": "Shelley",
    "last_name": "Vasnetsov",
    "email": "svasnetsove@booking.com",
    "gender": "Female"
  }, {
    "id": 16,
    "first_name": "Elfreda",
    "last_name": "Lorkin",
    "email": "elorkinf@eventbrite.com",
    "gender": "Non-binary"
  }, {
    "id": 17,
    "first_name": "Orelia",
    "last_name": "Sustin",
    "email": "osusting@ifeng.com",
    "gender": "Female"
  }, {
    "id": 18,
    "first_name": "Carline",
    "last_name": "Ciccone",
    "email": "ccicconeh@theguardian.com",
    "gender": "Female"
  }, {
    "id": 19,
    "first_name": "Mathias",
    "last_name": "Abelovitz",
    "email": "mabelovitzi@theatlantic.com",
    "gender": "Male"
  }, {
    "id": 20,
    "first_name": "Lurette",
    "last_name": "Shawcross",
    "email": "lshawcrossj@discuz.net",
    "gender": "Female"
  }]

export default dummyData;